### ISSUE TITLE
Problem with first example: No module named sip

### ISSUE THREAD

**Issue by ninafiona** [SoMa-Project/ec_grasp_planner#62]
Ubuntu 18.04, ros melodic, Python 2.7

I tried the first example, but received an error (see below) when running the command `rosrun ec_grasp_planner planner.py --rviz --robot_base_frame camera_rgb_optical_frame`

```
Traceback (most recent call last):
  File ".../ec_grasp_planner/ec_grasp_planner/src/planner.py", line 61, in <module>
    import tf_conversions.posemath as pm
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf_conversions/__init__.py", line 30, in <module>
    from .posemath import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf_conversions/posemath.py", line 34, in <module>
    from PyKDL import *
ImportError: No module named sip
```

Update: It seems to be this problem: https://github.com/orocos/orocos_kinematics_dynamics/issues/287
I removed all ros packages that are dependend on orocos_kinematics_dynamics and installed orocos_kinematics_dynamics from source and the import of PyKDL succeeded. With the ros packages installed (maybe with a different version of KDL) there is the error 'No module named sip' when importing PyKDL. 

I also posted this issue here: 
* https://github.com/ros/geometry/issues/215 
* https://answers.ros.org/question/363397/cannot-import-tf_conversions/

**Comment by zweistein** [comment]
this happens on TAG ms4.5 but not on MS4b_Elod

**Comment by ninafiona** [comment]
Update: I commented out the import of tf_conversions and rewrote the functions to work without KDL. Not tested yet due to an error with another package, but I guess it should work with this workaround.
